name: Selenium Java BDD Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 1.8

    - name: Install Maven
      run: sudo apt-get install -y maven

    - name: Build with Maven
      run: mvn clean install

    - name: Run Selenium tests
      run: mvn verify
