name: Selenium JUnit Cucumber Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 1.8
        distribution: 'corretto'

    - name: Install Chrome browser
      run: sudo apt-get update && sudo apt-get install -y google-chrome-stable

    - name: Download and install ChromeDriver
      run: |
        LATEST_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        curl -sS -o chromedriver.zip https://chromedriver.storage.googleapis.com/$LATEST_VERSION/chromedriver_linux64.zip
        unzip chromedriver.zip
        chmod +x chromedriver
        sudo mv chromedriver /usr/local/bin/

    - name: Install dependencies and run tests
      run: |
        sudo apt-get install -y maven
        mvn clean test -Dtest=com.example.TestRunner
      env:
        CHROME_DRIVER_PATH: /usr/local/bin/chromedriver
